### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by alexkelley** [jscott1989/python-pipedrive#13]
Hello Jonathan,

I was wondering if you were still using this wrapper.  I'm working on my own so thought to collaborate if this was still an active interest of yours.

FYI, I saw your comment about Devbridge's jquery.autocomplete.js tool.  I work at Devbridge--small world :-)

Best,

Alex

**Comment by jscott1989** [comment]
Hi Alex,

I haven't used Pipedrive in many years. I mostly just merge things occasionally when people ask. If you'd like to take over this wrapper I'm happy to transfer ownership as I'm not a great steward of it given I don't use Pipedrive.

Also, that line was added by https://github.com/jayache80 - I've never heard of jquery.autocomplete :p I'm sure it's nice though.
