### ISSUE TITLE
No way to test the sandbox environment

### ISSUE THREAD

**Issue by redhat-raptor** [jscott1989/python-pipedrive#16]
Currently, the API URL is hardcoded in the code hence there is no way to test the API calls in the Sandbox environment.

Something like following would allow better handling the API URL:
```
def __init__(self, api_url, email, password=None):
    self.api_url = api_url if api_url else 'https://api.pipedrive.com/v1/'
...
uri = self.api_url + endpoint + '?api_token=' + str(self.api_token)
```

**Comment by MatheusAmelco** [comment]
It is possible to send requests to a sandbox environment with the URI "https://api.pipedrive.com/v1/". Just enter your token that should work fine.

**Comment by redhat-raptor** [comment]
Ah... I see.. so, the token already identifies the env? I thought we would explicitly need to make requests to prod or sandbox! Thanks for clarifying!
