### ISSUE TITLE
Please provide a license

### ISSUE THREAD

**Issue by mmahut** [jscott1989/python-pipedrive#18]
Dear upstream, could you please provide a license for you project?

**Comment by Jamim** [comment]
Hello @mmahut,
I believe [the license is MIT](https://github.com/jscott1989/python-pipedrive/blob/master/setup.py#L6), but the `LICENSE` file is missing for some reason.

**Comment by mmahut** [comment]
@Jamim that is true, but as a downstream, we need to have it within the source code or in the file itself.
