### ISSUE TITLE
How can I install this package?

### ISSUE THREAD

**Issue by sowinski** [jscott1989/python-pipedrive#19]
Hi,

1) how can I install this library? 
2) Is it still working?

I tried:
pip3 install python-pipedrive

But import does not work.
```
>>> from pipedrive import Pipedrive
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'Pipedrive'

```

**Comment by matheusrossato** [comment]
Download the zip or clone this repo into yours project folder.

If zip, you can try pip install python-pipedrive-master.zip or in the IDE you can import the zip.
If cloned, python ./setup.py.

**Comment by sowinski** [comment]
Badly written code. I was able to fix my issue. Thank you
